# ::Commands::
# Build: sudo docker build -t i9e -f Dockerfile-i9e .
# Run: sudo docker run -it --network=host i9e:latest


FROM openkbs/jdk-mvn-py3
EXPOSE 8099
EXPOSE 9090
WORKDIR /usr/local/
RUN sudo mkdir i9e
WORKDIR /usr/local/i9e
RUN sudo wget https://gigaspaces-releases-eu.s3.amazonaws.com/insightedge/14.5.0/gigaspaces-insightedge-enterprise-14.5.0-m7.zip
RUN sudo unzip gigaspaces-insightedge-enterprise-14.5.0-m7.zip
WORKDIR /usr/local/i9e/gigaspaces-insightedge-enterprise-14.5.0-m7
RUN echo "tryme" | sudo tee xap-license.txt
WORKDIR /usr/local/
COPY src/edit-setenv-overrides.sh .
RUN ./edit-setenv-overrides.sh
COPY src/activate-i9e.sh .
COPY src/Consumer.py .
COPY src/final_model.joblib .
COPY src/activate-consumer.sh .
RUN sudo pip3 install kafka
COPY src/i9e-entrypoint.sh .
COPY src/full_train.csv .
COPY src/UberRecord.SCALA .
COPY src/IntializeUberRecordType.SCALA .
COPY src/copy-zeppelin-notebook.sh .
COPY src/LoadTrainDataToSpace.py .
ENTRYPOINT [ "./i9e-entrypoint.sh" ]
