# sudo docker build -t i9e -f Dockerfile-i9e .
# sudo docker run -it -p 8099:8099 -p 9090:9090 i9e:latest


FROM openkbs/jdk-mvn-py3
EXPOSE 8099
EXPOSE 9090
WORKDIR /usr/local/
RUN sudo mkdir i9e
WORKDIR /usr/local/i9e
RUN sudo wget https://gigaspaces-releases-eu.s3.amazonaws.com/insightedge/14.5.0/gigaspaces-insightedge-enterprise-14.5.0-m7.zip
RUN sudo unzip gigaspaces-insightedge-enterprise-14.5.0-m7.zip
WORKDIR /usr/local/i9e/gigaspaces-insightedge-enterprise-14.5.0-m7
RUN echo "tryme" | sudo tee xap-license.txt
WORKDIR /usr/local/
COPY src/activate-i9e.sh .
ENTRYPOINT [ "sudo", "./activate-i9e.sh"]

#CMD sudo nohup bash -c "bin/zookeeper-server-start.sh &" && sleep 10

